-
    name: Play 1
    hosts: localhost
    vars:
          out: "output"
    tasks:
        - name: Execute command 'date'
          command: date
          register: "{{out}}"

        - debug: var=output.stdout_lines
